eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

zuul:
  ignored-services: '*'
  routes:
    zgl-user:
      path: /v1.0/user/**
      stripPrefix: false
      serviceId: zgl-user

#logging:
#  level:
#    com.netflix: debug

server:
  port: 8080

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2500MB
