eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

zuul:
  ignored-services: "*"
  routes:
    user:
      path: /v1.0/user/**
      stripPrefix: false
      serviceId: User

server:
  port: 8080

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 1000MB