eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

zuul:
  ignored-services: "*"
  routes:
    user:
      path: /v1.0/user/**
      stripPrefix: false
      serviceId: User

server:
  port: 8080
